#!/bin/bash

linkfile=links.db
[[ -f "links-$HOSTNAME.db" ]] && linkfile="links-$HOSTNAME.db"

if [[ ! -f "$linkfile" ]]
then
	echo "No link db in current directory." >&2
	exit 1
fi

targetdir=${1:-$HOME}

while read -r
do
	OIFS=$IFS
	IFS=$'\t'
	set -- $REPLY
	IFS=$OIFS

	target=$1
	linkname=$2

	(
		cd "$targetdir"
		if [[ -L "$linkname" ]]
		then
			echo -n "$linkname" "-> "
			readlink -e "$linkname"
			rm -vf "$linkname"
			rmdir -vp "$(dirname "$linkname")"
		else
			tput bold
			tput setaf 1
			echo "LINK $linkname MISSING OR NOT A LINK!"
			tput sgr0
		fi
	)

done < "$linkfile"
