#!/bin/bash

if [[ ! -d .git ]]
then
	cat >&2 <<-EOF
	This script ($0) is meant to be called from the root of your git
	repo. The best way to do this is to use it as a hook.
	EOF
	exit 1
fi

linkdir=manage_links
linkfile="$linkdir/links.db"
[[ -f "$linkdir/links-$HOSTNAME.db" ]] && linkfile="$linkdir/links-$HOSTNAME.db"

if [[ ! -f "$linkfile" ]]
then
	echo "No link db found." >&2
	exit 1
fi

linkfile=$(readlink -e "$linkfile")

cd

while IFS=$'\t' read -r target linkname
do
	(
	if [[ -e "$linkname" ]]
	then
		if [[ ! -L "$linkname" ]]
		then
			echo "\`$linkname' exists and is not a symlink, will be deleted:"
			tree -aC "$linkname"
			rm -Rvi "$linkname"
		else
			rm -v "$linkname"
		fi
	fi

	mkdir -p "$(dirname "$linkname")"
	ln -svi "$target" "$linkname"
	) < /dev/tty

	echo
done < "$linkfile"

cat <<EOF

Remember:

This script does not clean up old symlinks which are no longer tracked.
You may want to perform a manual clean up from time to time:

	find ~ -type l ! -exec test -r {} \; -print

This process is not automated because it takes a very long time to scan
your whole home directory.

EOF
