#!/bin/bash

linkfile=links.db
[[ -f "links-$HOSTNAME.db" ]] && linkfile="links-$HOSTNAME.db"

if [[ ! -f "$linkfile" ]]
then
	echo "No link db in current directory." >&2
	exit 1
fi

targetdir=${1:-$HOME}

while read -r
do
	OIFS=$IFS
	IFS=$'\t'
	set -- $REPLY
	IFS=$OIFS

	target=$1
	linkname=$2

	(
		cd "$targetdir"
		echo mkdir -p "$(dirname "$linkname")"
		mkdir -p "$(dirname "$linkname")"
		echo ln -svi "$target" "$linkname"
		ln -svi "$target" "$linkname" < /dev/tty
	)

done < "$linkfile"
