# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1356973753);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.dir", "/tmp/download");
user_pref("browser.download.folderList", 2);
user_pref("browser.formfill.enable", false);
user_pref("browser.migration.version", 8);
user_pref("browser.newtab.url", "about:blank");
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.startup.homepage", "file://__USER_HOME__/work/dotfiles/bookmarks.xhtml");
user_pref("browser.startup.homepage_override.buildID", "20130119064747");
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.tabs.closeWindowWithLastTab", false);
user_pref("browser.tabs.insertRelatedAfterCurrent", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.urlbar.trimURLs", false);
user_pref("dom.mozApps.used", true);
user_pref("extensions.adblockplus.currentVersion", "2.2.1");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"version\":\"2.2.1\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/extensions/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:18.0.1");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"overbiteff@floodgap.com\":{\"descriptor\":\"/usr/lib/firefox/extensions/overbiteff@floodgap.com\",\"mtime\":1359310013000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1358579288000},\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\",\"mtime\":1353669842000}}}]");
user_pref("extensions.lastAppVersion", "18.0.1");
user_pref("extensions.lastPlatformVersion", "18.0.1");
user_pref("extensions.overbiteff.buildmark", 1627);
user_pref("extensions.pendingOperations", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20130206211324");
user_pref("gecko.mstone", "18.0.2");
user_pref("general.smoothScroll", false);
user_pref("general.warnOnAboutConfig", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("layout.spellcheckDefault", 0);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dnsCacheExpiration", 0);
user_pref("places.history.expiration.transient_current_max_pages", 13264);
user_pref("pdfjs.disabled", true);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.rememberSignons", false);
user_pref("toolkit.startup.last_success", 1359197364);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1359565757);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
