(define custom-activate-default-im-name? #t)
(define custom-preserved-default-im-name 'm17n-bo-wylie)
(define default-im-name 'm17n-bo-wylie)
(define enabled-im-list '(anthy anthy-utf8 skk tutcode byeoru latin elatin m17n-ug-kbd m17n-ua-kbd m17n-th-tis820 m17n-th-pattachote m17n-th-kesmanee m17n-te-itrans m17n-ta-lk-renganathan m17n-ta-itrans m17n-sv-post m17n-sr-kbd m17n-sk-kbd m17n-si-wijesekera m17n-si-samanala m17n-sa-harvard-kyoto m17n-ru-yawerty m17n-ru-phonetic m17n-ru-kbd m17n-pa-itrans m17n-or-itrans m17n-my-kbd m17n-ml-itrans m17n-lo-lrt m17n-lo-kbd m17n-ko-romaja m17n-ko-han2 m17n-kn-itrans m17n-km-yannis m17n-kk-kbd m17n-kk-arabic m17n-ka-kbd m17n-ja-trycode m17n-ja-tcode m17n-ja-anthy m17n-en-ispell m17n-hy-kbd m17n-hr-kbd m17n-hi-typewriter m17n-hi-itrans m17n-he-kbd m17n-gu-itrans m17n-grc-mizuochi m17n-fr-azerty m17n-fa-isiri m17n-el-kbd m17n-dv-phonetic m17n-da-post m17n-cmc-kbd m17n-bo-wylie m17n-bo-tcrc m17n-bn-unijoy m17n-bn-itrans m17n-as-itrans m17n-ar-kbd m17n-am-sera m17n-unicode m17n-syrc-phonetic m17n-rfc1345 m17n-latn-pre m17n-latn-post m17n-zh-tonepy m17n-zh-tonepy-gb m17n-zh-tonepy-b5 m17n-zh-quick m17n-zh-py m17n-zh-py-gb m17n-zh-py-b5 m17n-zh-pinyin m17n-zh-cangjie m17n-zh-bopomofo m17n-vi-telex m17n-vi-tcvn m17n-vi-vni m17n-vi-viqr zm wb86 py pyunihan pinyin-big5 viqr ipa-x-sampa look ajax-ime social-ime google-cgiapi-jp baidu-olime-jp))
(define enable-im-switch? #f)
(define switch-im-key '("<Control>Shift_key" "<Shift>Control_key"))
(define switch-im-key? (make-key-predicate '("<Control>Shift_key" "<Shift>Control_key")))
(define switch-im-skip-direct-im? #f)
(define enable-im-toggle? #f)
(define toggle-im-key '("<Control>Shift_key"))
(define toggle-im-key? (make-key-predicate '("<Control>Shift_key")))
(define toggle-im-alt-im 'direct)
(define uim-color 'uim-color-uim)
(define candidate-window-style 'vertical)
(define candidate-window-position 'caret)
(define enable-lazy-loading? #t)
(define bridge-show-input-state? #f)
(define bridge-show-with? 'time)
(define bridge-show-input-state-time-length 3)
